from pathlib import Path

from pmigrate.agent.diff import parse_unified_diff
from pmigrate.agent.patch import apply_patch, check_invariants, is_test_path


def _write(repo: Path, rel_path: str, content: str) -> None:
    full = repo / rel_path
    full.parent.mkdir(parents=True, exist_ok=True)
    full.write_text(content)


def _diff(a_path: str, old: str, new: str) -> str:
    """A minimal, real unified diff between two single-line-per-item file contents,
    generated by hand in the exact format git produces (context line + -old + +new)."""
    old_lines = old.splitlines()
    new_lines = new.splitlines()
    body = []
    for line in old_lines:
        body.append(f"-{line}")
    for line in new_lines:
        body.append(f"+{line}")
    return (
        f"diff --git a/{a_path} b/{a_path}\n"
        f"--- a/{a_path}\n"
        f"+++ b/{a_path}\n"
        f"@@ -1,{len(old_lines)} +1,{len(new_lines)} @@\n" + "\n".join(body) + "\n"
    )


# --- is_test_path -----------------------------------------------------------------


def test_is_test_path_matches_tests_directory() -> None:
    assert is_test_path("tests/test_models.py")
    assert is_test_path("app/tests/test_x.py")


def test_is_test_path_matches_test_prefix_and_suffix() -> None:
    assert is_test_path("test_models.py")
    assert is_test_path("models_test.py")


def test_is_test_path_matches_conftest() -> None:
    assert is_test_path("conftest.py")
    assert is_test_path("tests/conftest.py")


def test_is_test_path_false_for_normal_source() -> None:
    assert not is_test_path("app/models.py")
    assert not is_test_path("app/testing_utils.py")  # contains "test" but isn't a test file


# --- I1: no test file edits --------------------------------------------------------


def test_i1_blocks_diff_touching_test_file() -> None:
    diff = _diff("tests/test_models.py", "assert 1 == 1", "assert 1 == 2")
    violations = check_invariants(parse_unified_diff(diff))
    assert any(v.invariant == "I1" for v in violations)


def test_i1_allows_diff_touching_source_file() -> None:
    diff = _diff("app/models.py", "x = m.dict()", "x = m.model_dump()")
    violations = check_invariants(parse_unified_diff(diff))
    assert not any(v.invariant == "I1" for v in violations)


# --- I2: no skip/delete -------------------------------------------------------------


def test_i2_blocks_added_skip_marker() -> None:
    diff = _diff("app/helpers.py", "x = 1", "@pytest.mark.skip\nx = 1")
    violations = check_invariants(parse_unified_diff(diff))
    assert any(v.invariant == "I2" for v in violations)


def test_i2_blocks_deleted_test_function() -> None:
    diff = _diff("app/conftest_helpers.py", "def test_foo():\n    assert True", "pass")
    violations = check_invariants(parse_unified_diff(diff))
    assert any(v.invariant == "I2" and "test_foo" in v.message for v in violations)


def test_i2_allows_renamed_but_present_test_function() -> None:
    # a test function that's removed AND an identically-named one re-added (e.g. a
    # reformatted signature) should NOT be flagged as a deletion
    diff = _diff(
        "app/x.py",
        "def test_foo():\n    assert True",
        "def test_foo():\n    assert True is True",
    )
    violations = check_invariants(parse_unified_diff(diff))
    assert not any(v.invariant == "I2" for v in violations)


# --- I3: no pydantic v1 pin ----------------------------------------------------------


def test_i3_blocks_pydantic_lt_2_pin() -> None:
    diff = _diff("requirements.txt", "pydantic>=2", "pydantic<2")
    violations = check_invariants(parse_unified_diff(diff))
    assert any(v.invariant == "I3" for v in violations)


def test_i3_blocks_pydantic_exact_v1_pin() -> None:
    diff = _diff("pyproject.toml", 'pydantic = ">=2"', 'pydantic = "==1.10"')
    violations = check_invariants(parse_unified_diff(diff))
    assert any(v.invariant == "I3" for v in violations)


def test_i3_allows_pydantic_v2_pin() -> None:
    diff = _diff("requirements.txt", "pydantic", "pydantic>=2,<3")
    violations = check_invariants(parse_unified_diff(diff))
    assert not any(v.invariant == "I3" for v in violations)


def test_i3_ignores_non_dependency_files() -> None:
    # "pydantic<2" appearing in a comment inside a source file isn't a real dependency pin
    diff = _diff("app/notes.py", "# old", "# pydantic<2 was the old constraint")
    violations = check_invariants(parse_unified_diff(diff))
    assert not any(v.invariant == "I3" for v in violations)


# --- apply_patch end-to-end (real filesystem, no git repo needed) -------------------


def test_apply_patch_writes_file_on_clean_diff(tmp_path: Path) -> None:
    _write(tmp_path, "app/models.py", "x = m.dict()\n")
    diff = _diff("app/models.py", "x = m.dict()", "x = m.model_dump()")
    result = apply_patch(tmp_path, diff)
    assert result.applied is True
    assert result.files_changed == ("app/models.py",)
    assert (tmp_path / "app/models.py").read_text() == "x = m.model_dump()\n"


def test_apply_patch_rejects_test_file_edit_without_touching_disk(tmp_path: Path) -> None:
    _write(tmp_path, "tests/test_x.py", "assert 1 == 1\n")
    diff = _diff("tests/test_x.py", "assert 1 == 1", "assert 1 == 2")
    result = apply_patch(tmp_path, diff)
    assert result.applied is False
    assert any(v.invariant == "I1" for v in result.violations)
    # untouched — the file on disk is exactly what it was before
    assert (tmp_path / "tests/test_x.py").read_text() == "assert 1 == 1\n"


def test_apply_patch_reverts_on_post_apply_syntax_error(tmp_path: Path) -> None:
    _write(tmp_path, "app/broken.py", "x = 1\n")
    diff = _diff("app/broken.py", "x = 1", "x = (((1")
    result = apply_patch(tmp_path, diff)
    assert result.applied is False
    assert result.stderr is not None and "invalid syntax" in result.stderr
    # reverted — original content restored on disk
    assert (tmp_path / "app/broken.py").read_text() == "x = 1\n"


def test_apply_patch_empty_diff_is_a_no_op(tmp_path: Path) -> None:
    result = apply_patch(tmp_path, "")
    assert result.applied is True
    assert result.files_changed == ()


def test_apply_patch_fails_cleanly_on_diff_that_does_not_match_disk(tmp_path: Path) -> None:
    _write(tmp_path, "app/models.py", "completely different content\n")
    diff = _diff("app/models.py", "x = m.dict()", "x = m.model_dump()")
    result = apply_patch(tmp_path, diff)
    assert result.applied is False
    assert result.stderr  # git apply's own error message is surfaced
